steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/github.com/mauricio-dias-silva/scalabis:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/github.com/mauricio-dias-silva/scalabis:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'scalabis'
    - '--image'
    - 'gcr.io/$PROJECT_ID/github.com/mauricio-dias-silva/scalabis:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'DEBUG=False'

images:
- 'gcr.io/$PROJECT_ID/github.com/mauricio-dias-silva/scalabis:$COMMIT_SHA'