# Generated by Django 5.2.10 on 2026-01-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('slug', models.SlugField(help_text='URL amigável (ex: gestao-360)', unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('kiwifi_url', models.URLField(help_text='Link do checkout', verbose_name='Link KiwiFi')),
                ('cover_image', models.ImageField(upload_to='ebooks/', verbose_name='Capa do Ebook')),
                ('description', models.TextField(verbose_name='Descrição Curta')),
                ('long_description', models.TextField(blank=True, verbose_name='Descrição Completa (HTML)')),
                ('benefits', models.TextField(help_text='Liste os benefícios, um por linha', verbose_name='Benefícios (Um por linha)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ebook',
                'verbose_name_plural': 'Ebooks',
            },
        ),
    ]
