# Generated by Django 5.1.3 on 2026-01-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone/WhatsApp')),
                ('message', models.TextField(blank=True, verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('CONTACTED', 'Em Contato'), ('WON', 'Ganho'), ('LOST', 'Perdido')], default='NEW', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads (Clientes)',
                'ordering': ['-created_at'],
            },
        ),
    ]
