# Generated by Django 5.1.3 on 2026-01-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('icon', models.CharField(choices=[('fas fa-chess-queen', 'Rainha (Xadrez)'), ('fas fa-chart-pie', 'Gráfico (Pizza)'), ('fas fa-users', 'Pessoas/Equipe'), ('fas fa-briefcase', 'Maleta'), ('fas fa-lightbulb', 'Lâmpada (Ideia)'), ('fas fa-rocket', 'Foguete')], default='fas fa-briefcase', max_length=50, verbose_name='Ícone')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Estratégia e Liderança\nPara Negócios Reais', max_length=200, verbose_name='Título Herói')),
                ('hero_subtitle', models.TextField(default='Transformo empresários em líderes de alta performance através de consultoria estratégica e inteligência financeira.', verbose_name='Subtítulo Herói')),
                ('hero_button_text', models.CharField(default='Conheça Meus Materiais', max_length=50, verbose_name='Texto Botão Herói')),
                ('about_title', models.CharField(default='Olá, sou Dilvania Teixeira', max_length=100, verbose_name='Título Sobre')),
                ('about_description', models.TextField(default='Especialista em Educação Financeira e Gestão...', verbose_name='Descrição Sobre')),
                ('about_image', models.ImageField(blank=True, help_text='Se deixar em branco, usa a padrão.', null=True, upload_to='site/', verbose_name='Foto Sobre')),
                ('contact_phone', models.CharField(default='(11) 98267-5531', max_length=20, verbose_name='Telefone/WhatsApp')),
                ('contact_email', models.EmailField(default='dilvania.teixeira@dsop.com.br', max_length=254, verbose_name='Email')),
                ('contact_address', models.CharField(default='Carapicuíba - SP', max_length=200, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Configurações do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
