# Generated by Django 5.1.3 on 2026-01-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefits_title',
            field=models.CharField(default='O que você vai Aprender?', max_length=100, verbose_name='Título dos Benefícios'),
        ),
        migrations.AddField(
            model_name='product',
            name='cta_text',
            field=models.CharField(default='QUERO GARANTIR MINHA VAGA', max_length=50, verbose_name='Texto do Botão'),
        ),
        migrations.AddField(
            model_name='product',
            name='guarantee_text',
            field=models.CharField(default='Pagamento 100% Seguro via KiwiFi', max_length=100, verbose_name='Texto de Garantia'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_label',
            field=models.CharField(default='Investimento Único', max_length=50, verbose_name='Rótulo do Preço'),
        ),
    ]
