# Generated by Django 5.1.3 on 2026-01-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_benefits_title_product_cta_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bonus_spreadsheet',
            field=models.FileField(blank=True, help_text='Faça upload da planilha que será baixada na home.', null=True, upload_to='docs/', verbose_name='Planilha Bônus (CSV/Excel)'),
        ),
    ]
