# Generated by Django 5.1.3 on 2026-01-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_bonus_spreadsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bonus_button_text',
            field=models.CharField(default='BAIXAR "O MAPA DO TESOURO"', max_length=100, verbose_name='Texto do Botão'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bonus_image',
            field=models.ImageField(blank=True, help_text='Opcional. Substitui o ícone de presente.', null=True, upload_to='site/', verbose_name='Imagem/Ícone Personalizado'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bonus_subtitle',
            field=models.TextField(default='Eu preparei algo que você não encontra em lugar nenhum. Não é apenas uma planilha, é o Mapa do Tesouro da sua liberdade financeira.', verbose_name='Descrição do Bônus'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bonus_title',
            field=models.CharField(default='O "Pulo do Gato" que Faltava na Sua Gestão', max_length=200, verbose_name='Título do Bônus'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bonus_spreadsheet',
            field=models.FileField(blank=True, help_text='Faça upload da planilha que será baixada. Se vazio, usa a padrão.', null=True, upload_to='docs/', verbose_name='Planilha Bônus (CSV/Excel)'),
        ),
    ]
