# Generated by Django 5.2.10 on 2026-01-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_bonus_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Lucro Real Calculado'),
        ),
        migrations.AddField(
            model_name='lead',
            name='company_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Faturamento Declarado'),
        ),
        migrations.AddField(
            model_name='lead',
            name='health_status',
            field=models.CharField(blank=True, help_text='Diagnóstico automático do site', max_length=20, verbose_name='Saúde Financeira'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_intro',
            field=models.TextField(default='Se fizer sentido para você, este é um espaço para dar o próximo passo com clareza. Entre em contato para agendar uma conversa ou tirar dúvidas. Preencha o formulário abaixo', verbose_name='Texto Intro do Formulário'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ebook_section_subtitle',
            field=models.TextField(default='Guias práticos para organizar o dinheiro com clareza, método e decisões mais alinhadas à sua realidade', verbose_name='Subtítulo Seção Ebooks'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ebook_section_title',
            field=models.CharField(default='Educação Financeira Consciente', max_length=100, verbose_name='Título Seção Ebooks'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_termometro',
            field=models.BooleanField(default=False, verbose_name='Exibir Termômetro da Riqueza'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_widget_text',
            field=models.CharField(default='Falar comigo no WhatsApp', max_length=50, verbose_name='Texto Widget WhatsApp'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_address',
            field=models.CharField(default='Santana de Parnaíba - SP', max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='dillteixeira31@gmail.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(default='(11) 98999-6055', max_length=20, verbose_name='Telefone/WhatsApp'),
        ),
    ]
