# Generated by Django 5.2.10 on 2026-01-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lead_company_profit_lead_company_revenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='Imagem de fundo da seção Hero', null=True, upload_to='site/', verbose_name='Imagem de Fundo Herói'),
        ),
    ]
